### ISSUE TITLE
nmmn.dsp and 'stats example wavelet.ipynb' inconsistency

### ISSUE THREAD

**Issue by ea42gh** [rsnemmen/nmmn#2]
I recently updated my version of nmmn,
and found that the wa.reconstruction() method called from
https://gist.github.com/rsnemmen/baea0541c6cc23ae2fbe48421ffc838e
is now inconsistent.

**Comment by rsnemmen** [comment]
Thanks for letting me know. This might be happening because the wavelet module dependency has changed. I will look into it.

Rodrigo

**Comment by ea42gh** [comment]
My apologies: I was rebuilding my machine after a big crash,
and had forgotten I needed to install your patched version of wavelets.

The code in the gist works perfectly as is!

**Comment by rsnemmen** [comment]
Good to know!

Rodrigo
