### ISSUE TITLE
Missing import evalfun in predbandnl

### ISSUE THREAD

**Issue by Bovornpratch** [rsnemmen/nmmn#4]
I was calculating some linear regression using BSCES and wanted to plot the prediction limits. 
The module nmmn.stats.predbandnl raises a NameError exception saying that the function  evalfun is not defined.

looking at the code under stats.py suggest that we are just missing a import section and import names

from . import misc

I have fixed this myself on my installation but this is just an FYI

Thanks for making these nice tools!

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-14-7b93b8e3c651> in <module>
     23 lci_fb, uci_fb, xarray_fb = nmmn.stats.confbandnl(lir_fb, lx_fb, func, fitm_fb, covm_fb, 2, 0.95, xarray)
     24 
---> 25 lpi_sb, upi_sb, xarray_sb = nmmn.stats.predbandnl(lir_sb, lx_sb, func, fitm_sb, covm_sb, 2, 0.95, xarray)
     26 #lpi_hb, upi_hb, xarray_hb = nmmn.stats.predbandnl(lir_hb, lx_hb, func, fitm_hb, covm_hb, 2, 0.95, xarray)
     27 #lpi_fb, upi_fb, xarray_fb = nmmn.stats.predbandnl(lir_fb, lx_fb, func, fitm_fb, covm_fb, 2, 0.95, xarray)

~/.local/lib/python3.8/site-packages/nmmn/stats.py in predbandnl(xd, yd, fun, par, varcov, deg, conf, x)
    540 
    541         # Residual sum of squares
--> 542         rss=residual(yd, evalfun(fun,xd,par) )
    543 
    544         grad,p=[],[]

NameError: name 'evalfun' is not defined

**Comment by rsnemmen** [comment]
Hey, thanks for pointing this out! I fixed it now. 

Next time, feel free to do a pull request with the fix. 🙂
